# Generated by Django 4.0.2 on 2022-02-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('slug', models.SlugField(help_text='Unique name for this template when including it', unique=True)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL path for this page', unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.layout')),
            ],
        ),
    ]
