# Generated by Django 4.0.2 on 2022-02-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='title',
        ),
    ]
