# Generated by Django 4.0.2 on 2022-02-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_layout_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
