# Generated by Django 4.1.7 on 2023-06-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('BOOLEAN', 'Yes/No'), ('CHAR', 'Small amount of text'), ('TEXT', 'Bigger text entry'), ('CHOICE', 'Multiple Choice')], max_length=10)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_slug', models.SlugField(max_length=100)),
                ('email_required', models.BooleanField(default=True)),
                ('phone_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rallies.rally')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rallies.customquestion')),
            ],
        ),
        migrations.AddField(
            model_name='customquestion',
            name='rally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rallies.rally'),
        ),
    ]
