# Generated by Django 6.0.2 on 2026-02-23 04:30

import bakers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(default=2026, unique=True, verbose_name="Year"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Races",
                "verbose_name_plural": "Races",
            },
        ),
        migrations.CreateModel(
            name="RaceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(null=True, verbose_name="Day #")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "starting_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Starting Date & Time"
                    ),
                ),
                (
                    "starting_address",
                    models.TextField(
                        blank=True, default="", verbose_name="Starting Line Address"
                    ),
                ),
                (
                    "starting_address_coordinates",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Starting line location longitude and lattitude",
                    ),
                ),
                (
                    "starting_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Starting Line Short Name",
                    ),
                ),
                (
                    "finishing_address",
                    models.TextField(
                        blank=True, default="", verbose_name="Finish Line Address"
                    ),
                ),
                (
                    "finishing_address_coordinates",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Finish line location longitude and lattitude",
                    ),
                ),
                (
                    "finishing_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Finish Line Short Name",
                    ),
                ),
                (
                    "commentary",
                    models.TextField(
                        blank=True, default="", verbose_name="Day Commentary"
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="bakers.race",
                    ),
                ),
            ],
            options={
                "verbose_name": "Races day",
                "verbose_name_plural": "Races days",
                "ordering": ["day_number"],
                "unique_together": {("race", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=bakers.models.upload_to
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teams",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="RaceTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakers.race"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakers.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Participating team",
                "verbose_name_plural": "Participating teams",
                "unique_together": {("race", "team")},
            },
        ),
        migrations.CreateModel(
            name="RaceTeamTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finish_time",
                    models.TimeField(blank=True, null=True, verbose_name="Finish Time"),
                ),
                ("dnf", models.BooleanField(default=False, verbose_name="DNF")),
                (
                    "commentary",
                    models.TextField(
                        blank=True, default="", verbose_name="Team's Day Commentary"
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="bakers.raceday",
                    ),
                ),
                (
                    "race_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakers.raceteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Races time",
                "verbose_name_plural": "Races times",
                "ordering": ["finish_time"],
                "unique_together": {("day", "race_team")},
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bakers",
                        to="bakers.race",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="bakers.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teams Member",
                "verbose_name_plural": "Teams Members",
                "unique_together": {("team", "member", "race")},
            },
        ),
    ]
