# Generated by Django 6.0.2 on 2026-02-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0002_alter_raceday_starting_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="invited",
            field=models.BooleanField(default=True, verbose_name="Invited"),
        ),
    ]
