# Generated by Django 6.0.2 on 2026-02-23 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0003_teammembership_invited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamMembership",
            new_name="RaceTeamMembership",
        ),
    ]
