# Generated by Django 6.0.2 on 2026-02-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0004_rename_teammembership_raceteammembership"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="captain",
            new_name="manager",
        ),
    ]
