# Generated by Django 6.0.2 on 2026-02-24 03:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0005_rename_captain_team_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceday",
            name="previous_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_day",
                to="bakers.raceday",
            ),
        ),
        migrations.AddField(
            model_name="raceday",
            name="starting_is_previous_finish",
            field=models.BooleanField(
                default=False,
                verbose_name="Starting line is the same as previous day finish line",
            ),
        ),
        migrations.AlterField(
            model_name="raceday",
            name="starting_datetime",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 2, 24, 10, 0),
                verbose_name="Starting Date & Time",
            ),
        ),
    ]
