# Generated by Django 6.0.2 on 2026-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0006_raceday_previous_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="starting_address",
            field=models.TextField(
                blank=True, default="", verbose_name="Starting Line Address"
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="starting_address_coordinates",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Starting line location longitude and lattitude",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="starting_location",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Starting Line Short Name",
            ),
        ),
    ]
