# Generated by Django 6.0.2 on 2026-02-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0007_race_starting_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceday",
            name="day_off",
            field=models.BooleanField(default=False, verbose_name="Day off"),
        ),
    ]
