# Generated by Django 6.0.2 on 2026-02-28 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0008_raceday_day_off"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceday",
            name="starting_datetime",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 2, 28, 10, 0),
                verbose_name="Starting Date & Time",
            ),
        ),
    ]
