# Generated by Django 6.0.2 on 2026-02-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0009_alter_raceday_starting_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="starting_description",
            field=models.TextField(
                blank=True, default="", verbose_name="Starting Description"
            ),
        ),
    ]
