# Generated by Django 6.0.2 on 2026-02-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0010_race_starting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="year",
            field=models.CharField(
                default=2026, max_length=4, unique=True, verbose_name="Year"
            ),
        ),
    ]
