# Generated by Django 6.0.2 on 2026-02-28 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0011_alter_race_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="starting_datetime",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 2, 28, 10, 0),
                verbose_name="Meetup Date & Time",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="starting_address",
            field=models.TextField(
                blank=True, default="", verbose_name="Meetup Address"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="starting_address_coordinates",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Meetup location longitude and lattitude",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="starting_description",
            field=models.TextField(
                blank=True, default="", verbose_name="Meetup Description"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="starting_location",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Meetup Location Short Name",
            ),
        ),
    ]
