# Generated by Django 6.0.2 on 2026-02-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0012_race_starting_datetime_alter_race_starting_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="race",
            old_name="starting_address",
            new_name="meetup_address",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="starting_datetime",
            new_name="meetup_datetime",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="starting_description",
            new_name="meetup_description",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="starting_location",
            new_name="meetup_location",
        ),
        migrations.RemoveField(
            model_name="race",
            name="starting_address_coordinates",
        ),
        migrations.AddField(
            model_name="race",
            name="meetup_address_coordinates",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Meetup location longitude and lattitude",
            ),
        ),
    ]
