# Generated by Django 6.0.2 on 2026-02-13 04:06

import bakers.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(default=2026, unique=True, verbose_name="Year"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Races",
                "verbose_name_plural": "Races",
            },
        ),
        migrations.CreateModel(
            name="RaceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(null=True, verbose_name="Day #")),
                (
                    "starting_time",
                    models.TimeField(
                        default=datetime.time(10, 0), verbose_name="Starting time"
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="bakers.race",
                    ),
                ),
            ],
            options={
                "verbose_name": "Races day",
                "verbose_name_plural": "Races days",
                "ordering": ["day"],
                "unique_together": {("race", "day")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=bakers.models.upload_to
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teams",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="RaceTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakers.race"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakers.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Participating team",
                "verbose_name_plural": "Participating teams",
                "unique_together": {("race", "team")},
            },
        ),
        migrations.CreateModel(
            name="RaceTeamTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.IntegerField(blank=True, null=True, verbose_name="Hours"),
                ),
                (
                    "minutes",
                    models.IntegerField(blank=True, null=True, verbose_name="Minutes"),
                ),
                ("dnf", models.BooleanField(default=False, verbose_name="DNF")),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="bakers.raceday",
                    ),
                ),
                (
                    "race_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakers.raceteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Races time",
                "verbose_name_plural": "Races times",
                "ordering": ["hours", "minutes"],
                "unique_together": {("day", "race_team")},
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bakers",
                        to="bakers.race",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="bakers.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teams Member",
                "verbose_name_plural": "Teams Members",
                "unique_together": {("team", "member", "race")},
            },
        ),
    ]
