# Generated by Django 6.0.2 on 2026-02-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raceteamtime",
            options={
                "ordering": ["minutes_total"],
                "verbose_name": "Races time",
                "verbose_name_plural": "Races times",
            },
        ),
        migrations.RemoveField(
            model_name="raceteamtime",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="raceteamtime",
            name="minutes",
        ),
        migrations.AddField(
            model_name="raceteamtime",
            name="minutes_total",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Minutes Total"
            ),
        ),
    ]
