# Generated by Django 6.0.2 on 2026-02-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bakers",
            "0002_alter_raceteamtime_options_remove_raceteamtime_hours_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raceteamtime",
            options={
                "ordering": ["duration"],
                "verbose_name": "Races time",
                "verbose_name_plural": "Races times",
            },
        ),
        migrations.RemoveField(
            model_name="raceteamtime",
            name="minutes_total",
        ),
        migrations.AddField(
            model_name="raceteamtime",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Minutes Total"
            ),
        ),
    ]
